# vim ft=yaml
language: python

python:
  - 3.5
  #- 3.6
  #- 3.7

cache:
  - apt

before_install:
  # The ultimate one-liner setup for NeuroDebian repository
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install eatmydata  # to speedup some installations
  - sudo tools/prep-travis-forssh-sudo.sh
  - tools/prep-travis-forssh.sh
  # Install optionally upstream current development so we are sure that they break nothing important for us
  - if [ ! -z "${_DL_UPSTREAM_GITANNEX:-}" ]; then sudo tools/install-annex-snapshot.sh; sudo ln -s `find /usr/local/lib/git-annex.linux -maxdepth 1 -type f -perm /+x` /usr/local/bin/; else sudo eatmydata apt-get install git-annex-standalone ; fi
  # Install optionally -devel version of annex, and if goes wrong (we have most recent), exit right away
  - if [ ! -z "${_DL_DEVEL_ANNEX:-}" ]; then tools/prep-travis-devel-annex.sh || exit 0; fi
  # Optionally install the latest Git.  Exit code 100 indicates that bundled is same as the latest.
  - if [ ! -z "${_DL_UPSTREAM_GIT:-}" ]; then sudo tools/install-latest-git.sh || [ $? -eq 100 ] && exit 0; fi

install:
  # Install standalone build of git-annex for the recent enough version
  - travis_retry sudo eatmydata apt-get install p7zip-full
  - git config --global user.email "test@travis.land"
  - git config --global user.name "Travis Almighty"
  - cd ..; pip install -q codecov; cd -
  - pip install -r requirements-devel.txt
  - sudo sed -i -e 's/^Defaults.*secure_path.*$//' /etc/sudoers
  # TMPDIRs
  - if [[ "${TMPDIR:-}" =~ .*/sym\ link ]]; then echo "Symlinking $TMPDIR"; ln -s /tmp "$TMPDIR"; fi
  # Test installation system-wide
  - sudo pip install .

script:
  - which git-annex-remote-ria
  - mkdir -p __testhome__
  - cd __testhome__
  # Run tests
  - http_proxy=
    python -m nose -s
      --with-doctest
      --logging-level=INFO
      ria_remote
  - cd ..
